//import './authFirebase';
//import './habits';
//import './register';
//import './setting';
import './challenges.js';
import './analytics.js'
import './home.js';
import './habits.js'
import './profile.js'